Add a setup.py to make eqcat installable
GEMScienceTools/catalogue_toolkit pull request #23
Opened 2017-02-23 18:01 UTC by daniviga

Makes `eqcat` installable by pip/setuptools

```bash
virtualenv foo
source foo/bin/activate

git clone https://github.com/GEMScienceTools/catalogue_toolkit.git
cd catalogue_toolkit
# install the catalogue_toolkit
pip install -e .
# install ipython and run the notebooks
pip install jupyter ipython notebook
jupyter notebook
```

2017-07-19 06:56 UTC, g-weatherill requested changes
Thanks for adding this Daniele. I have just added a new feature that requires (optionally) the geojson package for the toolkit. Is it possible to add that to the requirements list?
Otherwise LGTM

2017-07-20 08:31 UTC, daniviga commented
Hi @g-weatherill!

Yes, `setuptools` supports optional dependencies using the syntax `package[option]`, but if the dependency is trivial (i.e. small and pure python) I would suggest to add it to the main dependencies even if not always used.

2017-07-20 08:43 UTC, g-weatherill commented
Thanks Daniele, I think the geojson package is pretty small and pure Python (https://pypi.python.org/pypi/geojson), so it may as well go into the main dependencies.

2017-07-20 09:05 UTC, g-weatherill approved these changes

2017-07-20 09:06 UTC, merged